### ISSUE TITLE
change of j-novel api

### ISSUE THREAD

**Issue by kyndair** [Anpanator/jnc-downloader#8]
update to newer api as per [forum post](https://forums.j-novel.club/post/96770)

**Comment by Anpanator** [comment]
For documentation purposes:

> I'd like to request that you use this newer API in your tool to redeem credits. It's now being used on the current site as well: `POST https://labs.j-novel.club/app/v1/me/redeem/<volume ID or slug>`. Prefer using the volume ID over the slug, slug support is only there for legacy reasons. The possible response codes are:
> 
> 204: Success
> 401: Unauthorized
> 410: Session token expired
> 404: Volume not found
> 501: Can't buy manga at this time
> 402: No credits left to redeem
> 409: Already own this volume
> 500: Internal server error (reported to us)
> Other: Unknown server error
> Authenticate by passing a header Authorization: Bearer <access token>, or URL paramter access_token, but prefer the header method!

**Comment by Anpanator** [comment]
Changed in experimental branch.
